openapi: '3.0.0'
info:
  version: '1.0'
  title: Pothole Complaints API
  description: "This is the API specification which is used for the Serverless Backend Service for the Pothole Complaints Manager"
paths:
  /complaints:
    get:
      operationId: getComplaints
      parameters:
        - name: page
          in: query
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PotholeComplaint'
    post:
      operationId: postComplaint
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PotholeComplaint'
      responses:
        '201':
          description: Complaint created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PotholeComplaint'
        '400':
          description: Bad request
        '500':
          description: Server error
components:
  schemas:
    PotholeComplaint:
      type: object
      required:
        - latitude
        - longitude
        - streetName
      properties:
        streetName:
          type: string
        comments:
          type: string
        latitude:
          type: number
          format: double
        longitude:
          type: number
          format: double
        nearbyLandmark:
          type: string
        status:
          type: string
        base64Images:
          type: array
          items:
            type: string
    Error:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
