Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: app.lambda.CreateComplaintsProvider
      CodeUri: D:\bloomtech\unit5\Rutuj-Pothole-Complaint-Form\Pothole-Complaint-Form\App
      Runtime: java21
      Architectures:
        - x86_64